# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [1]:
import numpy as np  

In [2]:
arr1=np.array([0,1,2,3,4,5,6,7,8,9])
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr3=np.ones((2,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
arr4=np.identity(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

(2, 3)
int32
2
6



## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [7]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [8]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[:2,:]

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
arr[:,-1]

array([30, 60, 90])

In [11]:
arr[1,2]

60

In [12]:
arr[::-1,:]

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])


---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [13]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

In [14]:
even_number=arr[arr% 2 == 0]
even_number

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [15]:
arr[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [16]:
arr[:,-2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [17]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])


---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1+arr2

array([5, 7, 9])

In [19]:
arr1*arr2

array([ 4, 10, 18])

In [20]:
print(np.power(arr1,2))
print(np.power(arr2,2))

[1 4 9]
[16 25 36]



## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [21]:
A= np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

In [22]:
A+np.arange(0,3)
# or
A+B

array([[11, 22, 33],
       [14, 25, 36]])

In [23]:
A*B

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [24]:
A-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [25]:
A+C

array([[2, 3, 4],
       [6, 7, 8]])


---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [26]:
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

In [27]:
A+B

array([[100, 201, 302, 403],
       [104, 205, 306, 407],
       [108, 209, 310, 411]])

In [28]:
B=B.reshape(1,4)
aerr3=C*B
aerr3.shape

(3, 4)

In [29]:
A+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])


---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [30]:
arr = np.arange(12)

In [31]:
arr=arr.reshape(3,4)

In [32]:
arr=arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [33]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [34]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
arr3=np.arange(16).reshape(4,4)
arr3.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])


## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [36]:
arr = np.array([[5, 10, 15], [20, 25, 30]])
arr

array([[ 5, 10, 15],
       [20, 25, 30]])

In [37]:
arr[arr>10]

array([15, 20, 25, 30])

In [38]:
np.where(arr%2==0,-1,arr)

array([[ 5, -1, 15],
       [-1, 25, -1]])


---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.sum(arr)

21

In [41]:
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

In [42]:
np.max(arr,axis=1)

array([3, 6])

In [43]:
np.std(arr)

1.707825127659933


---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [44]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [45]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [46]:
A@B

array([[19, 22],
       [43, 50]])


---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [47]:
np.random.rand(2,3)

array([[0.19730913, 0.16158212, 0.61439455],
       [0.50324255, 0.33913955, 0.5364559 ]])

In [48]:
np.random.randint(50,100,10)

array([94, 73, 70, 62, 88, 64, 61, 80, 99, 65])


---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [49]:
matrix=np.array([[1,2],[3,4]])
np.linalg.matrix_rank(matrix)

2

In [50]:
inverse=np.linalg.inv(matrix)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [51]:
deterimne=np.linalg.det(matrix)
deterimne

-2.0000000000000004


## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [52]:
import numpy as np

In [53]:
array=np.random.randint(1,100,(6,6))
submatrices=[ array[i:i+3,j:j+3] for i in range(4) for j in range(4)]
submatrices

[array([[80,  6,  3],
        [39, 65, 38],
        [79, 50, 19]]),
 array([[ 6,  3, 36],
        [65, 38, 33],
        [50, 19,  5]]),
 array([[ 3, 36,  5],
        [38, 33, 99],
        [19,  5, 77]]),
 array([[36,  5, 64],
        [33, 99, 64],
        [ 5, 77, 48]]),
 array([[39, 65, 38],
        [79, 50, 19],
        [47, 86, 70]]),
 array([[65, 38, 33],
        [50, 19,  5],
        [86, 70, 28]]),
 array([[38, 33, 99],
        [19,  5, 77],
        [70, 28, 32]]),
 array([[33, 99, 64],
        [ 5, 77, 48],
        [28, 32, 76]]),
 array([[79, 50, 19],
        [47, 86, 70],
        [41, 47, 86]]),
 array([[50, 19,  5],
        [86, 70, 28],
        [47, 86, 14]]),
 array([[19,  5, 77],
        [70, 28, 32],
        [86, 14, 96]]),
 array([[ 5, 77, 48],
        [28, 32, 76],
        [14, 96, 46]]),
 array([[47, 86, 70],
        [41, 47, 86],
        [ 6, 16, 40]]),
 array([[86, 70, 28],
        [47, 86, 14],
        [16, 40, 27]]),
 array([[70, 28, 32],
        [86, 14, 96],
    